### ISSUE TITLE
Possible Input from repl command/service call?

### ISSUE THREAD

**Issue by kevyworks** [moleculerjs/moleculer-repl#22]
Hi @icebob,

I wish to know if it is possible to interact with a system process requesting an input like executing a script that requires sudo password. This is both for like a critical admin only services and repl commands.

**Comment by icebob** [comment]
I don't understand. Could you explain?

**Comment by kevmt** [comment]
Hi @icebob, well the idea was for a service which is only for repl and to prompt the admin user. like a param that asks input instead of `call sysctl.chpwd --old "123" --pwd "456"` to just `call sysctl.chpwd` pseudo:

```javascript
...
timeout: 0,
params: {
   old: { type: "string", $prompt: "Enter old Password: ", $mask: true },
   ...
}
...
```

```sh
mol $ call sysctl.chpwd
PROMPT node/SYSCTL Enter old Password: 
PROMPT node/SYSCTL Enter new Password:
INFO Password changed.
mol $ 
```

Can be just a replCommands but I think It would be easy if it is a service so `moleculer connect` have the ability to interact with it. 

But, For now ill play with repl commands which moleculer uses vorpal.. and I also found a reference here: http://2ality.com/2018/05/child-process-streams.html

**Comment by davidnussio** [comment]
Action callback receive as third parameter helpers object and it has vorpal reference.
I am tried to use prompt from vorpal, I copied the prompt example from vorpal.js.org but it does not work. I think because the this context is not the vorpal expected context.
I didn't investigate, I installed inquirer separately

```js
const inquirer = require("inquirer");

module.exports = [
  {
    command: "chpwd",
    description: "Fake change password service",
    // alias: "",
    options: [],
    types: {},
    //parse(command, args) {},
    //validate(args) {},
    //help(args) {},
    // allowUnknownOptions: true,
    action(/*broker, args, helpers*/) {
      return inquirer
        .prompt([
          {
            type: "password",
            message: "Enter a password",
            name: "password1"
          },
          {
            type: "password",
            message: "Enter a masked password",
            name: "password2",
            mask: "*"
          }
        ])
        .then(answers => {
          // broker.call(...)
          console.log(JSON.stringify(answers, null, "  "));
        });
    }
  }
];
```
